# Generated by Django 4.2.2 on 2023-06-21 13:05

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[Petstagram.photos.validators.validate_file_size]),
        ),
    ]
