# Generated by Django 4.2.2 on 2023-06-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myplant_app', '0004_plant_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='profile',
        ),
    ]
